### Get all posts
GET http://localhost:4000/posts

### Get a single post
GET http://localhost:4000/posts/1

### Create posts
POST http://localhost:4000/posts
Content-Type:'application/json

{
  "title": "New post title",
  "likes": 0
}

### Update posts
PUT http://localhost:4000/posts/1
Content-Type:'application/json

{
  "title": "update title",
  "likes": 100
}

### Deletee posts
DELETE  http://localhost:4000/posts/1